trigger:
  - main

pool:
  name: MYSECONDPOOL

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'

  - script: |
      echo "Simulating deployment..."
      mkdir deployed
      copy target\*.jar deployed\
      echo "Deployment successful!"
    displayName: 'Simulate Deployment'

  - script: |
      echo "Contents of deployed folder:"
      dir deployed
    displayName: 'Verify Deployment Output'
